### ISSUE TITLE
authentication issue

### ISSUE THREAD

**Issue by ivaibhavraheja** [burakorkmez/whatsapp-clone#6]
the clerk middleware code is not working. I have written the updated middleware code even that is also not working

**Comment by deepthiiii4** [comment]
import { clerkMiddleware } from '@clerk/nextjs/server';

export default clerkMiddleware({
  // Optionally, you can include a list of public routes
  // publicRoutes: ['/sign-in', '/public-page'],
});

export const config = {
  matcher: [
    '/((?!.*\\..*|_next).*)', // Exclude static files and Next.js internal paths
    '/', // Include the homepage
    '/(api|trpc)(.*)' // Include API routes
  ],
};
use this instead

**Comment by ghost** [comment]
It didn't work . I was getting this error and i wrapped the ClerkProvider in that dynamic wrapper

```
Error: Clerk: useAuth() called in static mode, wrap this component in <ClerkProvider dynamic> to make auth data available during server-side rendering.
    at usePromisifiedAuth (/Users/monarchcoprs/Desktop/Whatsapp-Clone/whatsapp-clone/.next/server/chunks/ssr/node_modules_bae3ec._.js:22898:19)
    at useAuthFromClerk (/Users/monarchcoprs/Desktop/Whatsapp-Clone/whatsapp-clone/.next/server/chunks/ssr/node_modules_bae3ec._.js:5645:56)
    at ConvexProviderWithAuth (/Users/monarchcoprs/Desktop/Whatsapp-Clone/whatsapp-clone/.next/server/chunks/ssr/node_modules_bae3ec._.js:5458:62)
digest: "784848838"
```

**Comment by ghost** [comment]
This is the updated code. It works well with it.

```
import { clerkMiddleware, createRouteMatcher } from '@clerk/nextjs/server'

const isProtectedRoute = createRouteMatcher(['/(.*)'])

export default clerkMiddleware(async (auth, req) => {
    const { userId, redirectToSignIn } = await auth()

    if (!userId && isProtectedRoute(req)) {
        // Add custom logic to run before redirecting

        return redirectToSignIn()
    }
})

export const config = {
    matcher: [
        // Skip Next.js internals and all static files, unless found in search params
        '/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)',
        // Always run for API routes
        '/(api|trpc)(.*)',
    ],
}
```

**Comment by SaadRimeh** [comment]
I think clerk is not code for all the projects
